### ISSUE TITLE
research: General purpose approach for authenticated folding data

### ISSUE THREAD

**Issue by devloper** [pluto/web-prover-circuits#14]
Currently, we carry all data across AES folds via a large quantity of public inputs. This approach is not scalable and requires a messy abstraction for upstream users.

Instead, we should explore a committed data structure (merkle tree, poly commit, offline memory checking, etc) and open it at the relevant points in subsequent circuits. This will introduce a constant circuit overhead to each fold but will preserve the IVC that the current approach lacks.

The current approach is [commented out here](https://github.com/pluto/web-prover-circuits/blob/main/circuits/aes_gcm.circom#L17), but was temporarily used in the [upstream circuits](https://github.com/pluto/web-prover/blob/main/proofs/web_proof_circuits/aes_gcm/aes_gcm.circom#L17)

**Comment by 0xJepsen** [comment]
is this still the best place for this issue?

**Comment by 0xJepsen** [comment]
Maybe closed by #36

**Comment by Autoparallel** [comment]
Closed by #36
