### ISSUE TITLE
create NIVC implementation with `aes-proof` + `parser-attestor` circuits

### ISSUE THREAD

**Issue by lonerapier** [pluto/web-prover-circuits#19]
# Mission
Now that we have all the circuits needed in this repository, we should create an NIVC chain that uses `aes-proof` AES-GCTR implementation alongside the `parser-attestor` plaintext http locking +  json parsing scheme.

## Tasks
- [ ] Modify all the NIVC circuits to adopt the same parameters: `DATA_BYTES` and `MAX_STACK_HEIGHT`. Note that some circuits such as `JsonMaskObjectNIVC` will need a specific `maxKeyLen`. We should use `DATA_BYTES` and `MAX_STACK_HEIGHT` as parameters that define the `step_in/out` size for ALL NIVC circuits! `TOTAL_BYTES_ACROSS_NIVC` should not be necessary to have as an input as the calculation is given in the JSON parser template:
```
assert(MAX_STACK_HEIGHT >= 2);
    var PER_ITERATION_DATA_LENGTH = MAX_STACK_HEIGHT * 2 + 2;
    var TOTAL_BYTES_ACROSS_NIVC   = DATA_BYTES * (PER_ITERATION_DATA_LENGTH + 1) + 1;
``` 
- [ ] Write a test that tests the flow between `aes-proof` and `parser-attestor` circuits works properly for the set `DATA_SIZE`

---

For `MAX_STACK_HEIGHT`, 10 seems reasonable. For a test feel free to use smaller to make this faster.

**Comment by Autoparallel** [comment]
Let's get this closed.

**Comment by 0xJepsen** [comment]
Note on order: AES -> HTTP Parse -> http lock header -> http body mask -> json parse -> json_mask_object/json_mask_array -> extract value
