### ISSUE TITLE
update `parser-attestor` usage

### ISSUE THREAD

**Issue by Autoparallel** [pluto/web-prover-circuits#22]
# MIssion
Circuits and tests in `parser-attestor` have changed since the commit we brought in here. We should use the latest in `parser-attestor/main`

**Comment by 0xJepsen** [comment]
Going to bang this out.

**Comment by lonerapier** [comment]
I think this is duplicate of #19. We'll need to remove import of parser-attestor and use the newly brought in circuits directly
